server:
  port: 8067

spring:
  application:
    name: pay-module
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://39.96.33.132:3306/zlg_test?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
      username: root
      password: 123456
      initial-size: 5
      min-idle: 1
      max-active: 20
      max-wait: 60000
      min-evictable-idle-time-millis: 300000
      time-between-eviction-runs-millis: 60000
      validation-query: SELECT 1 FROM DUAL
      test-on-borrow: true
      pool-prepared-statements: true
      use-global-data-source-stat: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      filters: stat,wall
  output:
    ansi:
      enabled: detect

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml

pagehelper:
  reasonable: true
  supportMethodsArguments: true
  pageSizeZero: true
  params: count=countSql

logging:
  config: classpath:logback-spring.xml
  level:
    org:
      lg:
        pay:
          module:
            dao: debug


swagger2:
  enable: true


xxl:
  job:
    admin:
      addresses: http://10.0.0.43:9080/xxl-job-admin
    executor:
      appname: xxl-job-executor-sample
      ip:
      port: 9999
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30
    accessToken:


